// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proto/department/department.proto

package srv_tenant

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Department struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: gorm:"primary_key"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"type:int(11);not null;comment:'父级id'"
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty" gorm:"type:int(11);not null;comment:'父级id'"`
	// @inject_tag: gorm:"type:varchar(100);not null;comment:'名称'"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" gorm:"type:varchar(100);not null;comment:'名称'"`
	// @inject_tag: gorm:"type:varchar(100);not null;comment:'助记码'"
	MnemonicCode string `protobuf:"bytes,4,opt,name=mnemonic_code,json=mnemonicCode,proto3" json:"mnemonic_code,omitempty" gorm:"type:varchar(100);not null;comment:'助记码'"`
	// @inject_tag: gorm:"type:varchar(255);comment:'描述'"
	Desc string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty" gorm:"type:varchar(255);comment:'描述'"`
	// @inject_tag: gorm:"type:int(11);not null;comment:'租户id'"
	TenantId int32 `protobuf:"varint,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty" gorm:"type:int(11);not null;comment:'租户id'"`
	// @inject_tag: gorm:"type:tinyint(1);not null;default:1;comment:'启用'"
	Enable bool `protobuf:"varint,7,opt,name=enable,proto3" json:"enable,omitempty" gorm:"type:tinyint(1);not null;default:1;comment:'启用'"`
	// @inject_tag: gorm:"type:datetime;default:null"
	CreatedAt string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"type:datetime;default:null"`
	// @inject_tag: gorm:"type:datetime;default:null"
	UpdatedAt string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"type:datetime;default:null"`
	// @inject_tag: gorm:"type:datetime;default:null"
	DeletedAt string `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty" gorm:"type:datetime;default:null"`
}

func (x *Department) Reset() {
	*x = Department{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{0}
}

func (x *Department) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Department) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetMnemonicCode() string {
	if x != nil {
		return x.MnemonicCode
	}
	return ""
}

func (x *Department) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Department) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Department) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Department) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Department) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Department) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type GetDepartmentTreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId int32 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *GetDepartmentTreeRequest) Reset() {
	*x = GetDepartmentTreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartmentTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentTreeRequest) ProtoMessage() {}

func (x *GetDepartmentTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentTreeRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{1}
}

func (x *GetDepartmentTreeRequest) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetDepartmentTreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Department `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetDepartmentTreeResponse) Reset() {
	*x = GetDepartmentTreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartmentTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentTreeResponse) ProtoMessage() {}

func (x *GetDepartmentTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentTreeResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{2}
}

func (x *GetDepartmentTreeResponse) GetData() []*Department {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDepartmentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDepartmentInfoRequest) Reset() {
	*x = GetDepartmentInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartmentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentInfoRequest) ProtoMessage() {}

func (x *GetDepartmentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepartmentInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDepartmentInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Department `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetDepartmentInfoResponse) Reset() {
	*x = GetDepartmentInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepartmentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentInfoResponse) ProtoMessage() {}

func (x *GetDepartmentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{4}
}

func (x *GetDepartmentInfoResponse) GetData() *Department {
	if x != nil {
		return x.Data
	}
	return nil
}

type StoreDepartmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Department `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *StoreDepartmentRequest) Reset() {
	*x = StoreDepartmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDepartmentRequest) ProtoMessage() {}

func (x *StoreDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDepartmentRequest.ProtoReflect.Descriptor instead.
func (*StoreDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{5}
}

func (x *StoreDepartmentRequest) GetForm() *Department {
	if x != nil {
		return x.Form
	}
	return nil
}

type StoreDepartmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Department `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StoreDepartmentResponse) Reset() {
	*x = StoreDepartmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDepartmentResponse) ProtoMessage() {}

func (x *StoreDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDepartmentResponse.ProtoReflect.Descriptor instead.
func (*StoreDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{6}
}

func (x *StoreDepartmentResponse) GetData() *Department {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateDepartmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Department `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDepartmentRequest) GetForm() *Department {
	if x != nil {
		return x.Form
	}
	return nil
}

type UpdateDepartmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Department `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateDepartmentResponse) Reset() {
	*x = UpdateDepartmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentResponse) ProtoMessage() {}

func (x *UpdateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDepartmentResponse) GetData() *Department {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchBanDepartmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Ids  []int32 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *BatchBanDepartmentRequest) Reset() {
	*x = BatchBanDepartmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchBanDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBanDepartmentRequest) ProtoMessage() {}

func (x *BatchBanDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBanDepartmentRequest.ProtoReflect.Descriptor instead.
func (*BatchBanDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{9}
}

func (x *BatchBanDepartmentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BatchBanDepartmentRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchBanDepartmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BatchBanDepartmentResponse) Reset() {
	*x = BatchBanDepartmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_department_department_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchBanDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBanDepartmentResponse) ProtoMessage() {}

func (x *BatchBanDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_department_department_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBanDepartmentResponse.ProtoReflect.Descriptor instead.
func (*BatchBanDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_department_department_proto_rawDescGZIP(), []int{10}
}

func (x *BatchBanDepartmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_department_department_proto protoreflect.FileDescriptor

var file_proto_department_department_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x2f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x22,
	0x8d, 0x02, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x6e, 0x65,
	0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x37, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x16, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x45, 0x0a, 0x17,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73,
	0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x46, 0x0a, 0x18, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x41, 0x0a, 0x19, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x34, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61,
	0x6e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x81, 0x04, 0x0a, 0x11,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x24, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73,
	0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x73, 0x72, 0x76,
	0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0f, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x73,
	0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x2e, 0x73, 0x72,
	0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x42, 0x61, 0x6e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x25,
	0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x42, 0x61, 0x6e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_department_department_proto_rawDescOnce sync.Once
	file_proto_department_department_proto_rawDescData = file_proto_department_department_proto_rawDesc
)

func file_proto_department_department_proto_rawDescGZIP() []byte {
	file_proto_department_department_proto_rawDescOnce.Do(func() {
		file_proto_department_department_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_department_department_proto_rawDescData)
	})
	return file_proto_department_department_proto_rawDescData
}

var file_proto_department_department_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_department_department_proto_goTypes = []interface{}{
	(*Department)(nil),                 // 0: srv.tenant.Department
	(*GetDepartmentTreeRequest)(nil),   // 1: srv.tenant.GetDepartmentTreeRequest
	(*GetDepartmentTreeResponse)(nil),  // 2: srv.tenant.GetDepartmentTreeResponse
	(*GetDepartmentInfoRequest)(nil),   // 3: srv.tenant.GetDepartmentInfoRequest
	(*GetDepartmentInfoResponse)(nil),  // 4: srv.tenant.GetDepartmentInfoResponse
	(*StoreDepartmentRequest)(nil),     // 5: srv.tenant.StoreDepartmentRequest
	(*StoreDepartmentResponse)(nil),    // 6: srv.tenant.StoreDepartmentResponse
	(*UpdateDepartmentRequest)(nil),    // 7: srv.tenant.UpdateDepartmentRequest
	(*UpdateDepartmentResponse)(nil),   // 8: srv.tenant.UpdateDepartmentResponse
	(*BatchBanDepartmentRequest)(nil),  // 9: srv.tenant.BatchBanDepartmentRequest
	(*BatchBanDepartmentResponse)(nil), // 10: srv.tenant.BatchBanDepartmentResponse
}
var file_proto_department_department_proto_depIdxs = []int32{
	0,  // 0: srv.tenant.GetDepartmentTreeResponse.data:type_name -> srv.tenant.Department
	0,  // 1: srv.tenant.GetDepartmentInfoResponse.data:type_name -> srv.tenant.Department
	0,  // 2: srv.tenant.StoreDepartmentRequest.form:type_name -> srv.tenant.Department
	0,  // 3: srv.tenant.StoreDepartmentResponse.data:type_name -> srv.tenant.Department
	0,  // 4: srv.tenant.UpdateDepartmentRequest.form:type_name -> srv.tenant.Department
	0,  // 5: srv.tenant.UpdateDepartmentResponse.data:type_name -> srv.tenant.Department
	1,  // 6: srv.tenant.DepartmentService.GetDepartmentTree:input_type -> srv.tenant.GetDepartmentTreeRequest
	3,  // 7: srv.tenant.DepartmentService.GetDepartmentInfo:input_type -> srv.tenant.GetDepartmentInfoRequest
	5,  // 8: srv.tenant.DepartmentService.StoreDepartment:input_type -> srv.tenant.StoreDepartmentRequest
	7,  // 9: srv.tenant.DepartmentService.UpdateDepartment:input_type -> srv.tenant.UpdateDepartmentRequest
	9,  // 10: srv.tenant.DepartmentService.BatchBanDepartment:input_type -> srv.tenant.BatchBanDepartmentRequest
	2,  // 11: srv.tenant.DepartmentService.GetDepartmentTree:output_type -> srv.tenant.GetDepartmentTreeResponse
	4,  // 12: srv.tenant.DepartmentService.GetDepartmentInfo:output_type -> srv.tenant.GetDepartmentInfoResponse
	6,  // 13: srv.tenant.DepartmentService.StoreDepartment:output_type -> srv.tenant.StoreDepartmentResponse
	8,  // 14: srv.tenant.DepartmentService.UpdateDepartment:output_type -> srv.tenant.UpdateDepartmentResponse
	10, // 15: srv.tenant.DepartmentService.BatchBanDepartment:output_type -> srv.tenant.BatchBanDepartmentResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_department_department_proto_init() }
func file_proto_department_department_proto_init() {
	if File_proto_department_department_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_department_department_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Department); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartmentTreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartmentTreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartmentInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepartmentInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreDepartmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreDepartmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDepartmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDepartmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchBanDepartmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_department_department_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchBanDepartmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_department_department_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_department_department_proto_goTypes,
		DependencyIndexes: file_proto_department_department_proto_depIdxs,
		MessageInfos:      file_proto_department_department_proto_msgTypes,
	}.Build()
	File_proto_department_department_proto = out.File
	file_proto_department_department_proto_rawDesc = nil
	file_proto_department_department_proto_goTypes = nil
	file_proto_department_department_proto_depIdxs = nil
}
