// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/role/role.proto

package srv_permission

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoleService service

func NewRoleServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoleService service

type RoleService interface {
	GetRolePage(ctx context.Context, in *GetRolePageRequest, opts ...client.CallOption) (*GetRolePageResponse, error)
	StoreRole(ctx context.Context, in *StoreRoleRequest, opts ...client.CallOption) (*StoreRoleResponse, error)
	GetRoleInfo(ctx context.Context, in *GetRoleInfoRequest, opts ...client.CallOption) (*GetRoleInfoResponse, error)
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...client.CallOption) (*UpdateRoleResponse, error)
	BindUser(ctx context.Context, in *BindUserRequest, opts ...client.CallOption) (*BindUserResponse, error)
	BatchBanRole(ctx context.Context, in *BatchBanRoleRequest, opts ...client.CallOption) (*BatchBanRoleResponse, error)
}

type roleService struct {
	c    client.Client
	name string
}

func NewRoleService(name string, c client.Client) RoleService {
	return &roleService{
		c:    c,
		name: name,
	}
}

func (c *roleService) GetRolePage(ctx context.Context, in *GetRolePageRequest, opts ...client.CallOption) (*GetRolePageResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.GetRolePage", in)
	out := new(GetRolePageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleService) StoreRole(ctx context.Context, in *StoreRoleRequest, opts ...client.CallOption) (*StoreRoleResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.StoreRole", in)
	out := new(StoreRoleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleService) GetRoleInfo(ctx context.Context, in *GetRoleInfoRequest, opts ...client.CallOption) (*GetRoleInfoResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.GetRoleInfo", in)
	out := new(GetRoleInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleService) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...client.CallOption) (*UpdateRoleResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.UpdateRole", in)
	out := new(UpdateRoleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleService) BindUser(ctx context.Context, in *BindUserRequest, opts ...client.CallOption) (*BindUserResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.BindUser", in)
	out := new(BindUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleService) BatchBanRole(ctx context.Context, in *BatchBanRoleRequest, opts ...client.CallOption) (*BatchBanRoleResponse, error) {
	req := c.c.NewRequest(c.name, "RoleService.BatchBanRole", in)
	out := new(BatchBanRoleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoleService service

type RoleServiceHandler interface {
	GetRolePage(context.Context, *GetRolePageRequest, *GetRolePageResponse) error
	StoreRole(context.Context, *StoreRoleRequest, *StoreRoleResponse) error
	GetRoleInfo(context.Context, *GetRoleInfoRequest, *GetRoleInfoResponse) error
	UpdateRole(context.Context, *UpdateRoleRequest, *UpdateRoleResponse) error
	BindUser(context.Context, *BindUserRequest, *BindUserResponse) error
	BatchBanRole(context.Context, *BatchBanRoleRequest, *BatchBanRoleResponse) error
}

func RegisterRoleServiceHandler(s server.Server, hdlr RoleServiceHandler, opts ...server.HandlerOption) error {
	type roleService interface {
		GetRolePage(ctx context.Context, in *GetRolePageRequest, out *GetRolePageResponse) error
		StoreRole(ctx context.Context, in *StoreRoleRequest, out *StoreRoleResponse) error
		GetRoleInfo(ctx context.Context, in *GetRoleInfoRequest, out *GetRoleInfoResponse) error
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, out *UpdateRoleResponse) error
		BindUser(ctx context.Context, in *BindUserRequest, out *BindUserResponse) error
		BatchBanRole(ctx context.Context, in *BatchBanRoleRequest, out *BatchBanRoleResponse) error
	}
	type RoleService struct {
		roleService
	}
	h := &roleServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoleService{h}, opts...))
}

type roleServiceHandler struct {
	RoleServiceHandler
}

func (h *roleServiceHandler) GetRolePage(ctx context.Context, in *GetRolePageRequest, out *GetRolePageResponse) error {
	return h.RoleServiceHandler.GetRolePage(ctx, in, out)
}

func (h *roleServiceHandler) StoreRole(ctx context.Context, in *StoreRoleRequest, out *StoreRoleResponse) error {
	return h.RoleServiceHandler.StoreRole(ctx, in, out)
}

func (h *roleServiceHandler) GetRoleInfo(ctx context.Context, in *GetRoleInfoRequest, out *GetRoleInfoResponse) error {
	return h.RoleServiceHandler.GetRoleInfo(ctx, in, out)
}

func (h *roleServiceHandler) UpdateRole(ctx context.Context, in *UpdateRoleRequest, out *UpdateRoleResponse) error {
	return h.RoleServiceHandler.UpdateRole(ctx, in, out)
}

func (h *roleServiceHandler) BindUser(ctx context.Context, in *BindUserRequest, out *BindUserResponse) error {
	return h.RoleServiceHandler.BindUser(ctx, in, out)
}

func (h *roleServiceHandler) BatchBanRole(ctx context.Context, in *BatchBanRoleRequest, out *BatchBanRoleResponse) error {
	return h.RoleServiceHandler.BatchBanRole(ctx, in, out)
}
