// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proto/permission/permissionrole.proto

package srv_permission

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PermissionRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: gorm:"primary_key"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key"`
	// @inject_tag: gorm:"type:int(11);not null;comment:'权限id'"
	PermissionId int32 `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty" gorm:"type:int(11);not null;comment:'权限id'"`
	// @inject_tag: gorm:"type:int(11);not null;comment:'角色id'"
	RoleId int32 `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty" gorm:"type:int(11);not null;comment:'角色id'"`
	// @inject_tag: gorm:"type:datetime;default:null"
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"type:datetime;default:null"`
	// @inject_tag: gorm:"type:datetime;default:null"
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"type:datetime;default:null"`
}

func (x *PermissionRole) Reset() {
	*x = PermissionRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_permission_permissionrole_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRole) ProtoMessage() {}

func (x *PermissionRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permissionrole_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRole.ProtoReflect.Descriptor instead.
func (*PermissionRole) Descriptor() ([]byte, []int) {
	return file_proto_permission_permissionrole_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionRole) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionRole) GetPermissionId() int32 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *PermissionRole) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *PermissionRole) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PermissionRole) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_permission_permissionrole_proto protoreflect.FileDescriptor

var file_proto_permission_permissionrole_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x6f, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_permission_permissionrole_proto_rawDescOnce sync.Once
	file_proto_permission_permissionrole_proto_rawDescData = file_proto_permission_permissionrole_proto_rawDesc
)

func file_proto_permission_permissionrole_proto_rawDescGZIP() []byte {
	file_proto_permission_permissionrole_proto_rawDescOnce.Do(func() {
		file_proto_permission_permissionrole_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_permission_permissionrole_proto_rawDescData)
	})
	return file_proto_permission_permissionrole_proto_rawDescData
}

var file_proto_permission_permissionrole_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_permission_permissionrole_proto_goTypes = []interface{}{
	(*PermissionRole)(nil), // 0: srv.permission.PermissionRole
}
var file_proto_permission_permissionrole_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_permission_permissionrole_proto_init() }
func file_proto_permission_permissionrole_proto_init() {
	if File_proto_permission_permissionrole_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_permission_permissionrole_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_permission_permissionrole_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_permission_permissionrole_proto_goTypes,
		DependencyIndexes: file_proto_permission_permissionrole_proto_depIdxs,
		MessageInfos:      file_proto_permission_permissionrole_proto_msgTypes,
	}.Build()
	File_proto_permission_permissionrole_proto = out.File
	file_proto_permission_permissionrole_proto_rawDesc = nil
	file_proto_permission_permissionrole_proto_goTypes = nil
	file_proto_permission_permissionrole_proto_depIdxs = nil
}
