// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proto/sms/sms.proto

package srv_sms

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetLoginVerifyCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetLoginVerifyCodeRequest) Reset() {
	*x = GetLoginVerifyCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sms_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginVerifyCodeRequest) ProtoMessage() {}

func (x *GetLoginVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sms_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*GetLoginVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sms_sms_proto_rawDescGZIP(), []int{0}
}

func (x *GetLoginVerifyCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetLoginVerifyCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetLoginVerifyCodeResponse) Reset() {
	*x = GetLoginVerifyCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sms_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginVerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginVerifyCodeResponse) ProtoMessage() {}

func (x *GetLoginVerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sms_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginVerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*GetLoginVerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_sms_sms_proto_rawDescGZIP(), []int{1}
}

func (x *GetLoginVerifyCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetForgetPasswordCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetForgetPasswordCodeRequest) Reset() {
	*x = GetForgetPasswordCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sms_sms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetForgetPasswordCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForgetPasswordCodeRequest) ProtoMessage() {}

func (x *GetForgetPasswordCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sms_sms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForgetPasswordCodeRequest.ProtoReflect.Descriptor instead.
func (*GetForgetPasswordCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sms_sms_proto_rawDescGZIP(), []int{2}
}

func (x *GetForgetPasswordCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetForgetPasswordCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetForgetPasswordCodeResponse) Reset() {
	*x = GetForgetPasswordCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sms_sms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetForgetPasswordCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForgetPasswordCodeResponse) ProtoMessage() {}

func (x *GetForgetPasswordCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sms_sms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForgetPasswordCodeResponse.ProtoReflect.Descriptor instead.
func (*GetForgetPasswordCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_sms_sms_proto_rawDescGZIP(), []int{3}
}

func (x *GetForgetPasswordCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_sms_sms_proto protoreflect.FileDescriptor

var file_proto_sms_sms_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6d, 0x73, 0x2f, 0x73, 0x6d, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x72, 0x76, 0x2e, 0x73, 0x6d, 0x73, 0x22, 0x31,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x22, 0x34, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x46, 0x6f,
	0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x37, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xd7, 0x01, 0x0a, 0x0a, 0x53, 0x6d, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x72,
	0x76, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72,
	0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x25, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72,
	0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x73, 0x6d, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sms_sms_proto_rawDescOnce sync.Once
	file_proto_sms_sms_proto_rawDescData = file_proto_sms_sms_proto_rawDesc
)

func file_proto_sms_sms_proto_rawDescGZIP() []byte {
	file_proto_sms_sms_proto_rawDescOnce.Do(func() {
		file_proto_sms_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sms_sms_proto_rawDescData)
	})
	return file_proto_sms_sms_proto_rawDescData
}

var file_proto_sms_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sms_sms_proto_goTypes = []interface{}{
	(*GetLoginVerifyCodeRequest)(nil),     // 0: srv.sms.GetLoginVerifyCodeRequest
	(*GetLoginVerifyCodeResponse)(nil),    // 1: srv.sms.GetLoginVerifyCodeResponse
	(*GetForgetPasswordCodeRequest)(nil),  // 2: srv.sms.GetForgetPasswordCodeRequest
	(*GetForgetPasswordCodeResponse)(nil), // 3: srv.sms.GetForgetPasswordCodeResponse
}
var file_proto_sms_sms_proto_depIdxs = []int32{
	0, // 0: srv.sms.SmsService.GetLoginVerifyCode:input_type -> srv.sms.GetLoginVerifyCodeRequest
	2, // 1: srv.sms.SmsService.GetForgetPasswordCode:input_type -> srv.sms.GetForgetPasswordCodeRequest
	1, // 2: srv.sms.SmsService.GetLoginVerifyCode:output_type -> srv.sms.GetLoginVerifyCodeResponse
	3, // 3: srv.sms.SmsService.GetForgetPasswordCode:output_type -> srv.sms.GetForgetPasswordCodeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sms_sms_proto_init() }
func file_proto_sms_sms_proto_init() {
	if File_proto_sms_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sms_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginVerifyCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sms_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginVerifyCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sms_sms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetForgetPasswordCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sms_sms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetForgetPasswordCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sms_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sms_sms_proto_goTypes,
		DependencyIndexes: file_proto_sms_sms_proto_depIdxs,
		MessageInfos:      file_proto_sms_sms_proto_msgTypes,
	}.Build()
	File_proto_sms_sms_proto = out.File
	file_proto_sms_sms_proto_rawDesc = nil
	file_proto_sms_sms_proto_goTypes = nil
	file_proto_sms_sms_proto_depIdxs = nil
}
